<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SportSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $sport = ["Accrobranche",
            "Gymnastique acrobatique|Acrosport",
            "Aérobic",
            "Aéromodélisme",
            "Aérostation",
            "Agility",
            "Aïkido",
            "Airsoft",
            "Alpinisme",
            "Aquabiking",
            "Aquajogging",
            "Aquarunning",
            "Aquathlon",
            "Aquatriathlon",
            "Athlétisme",
            "Aviation",
            "Aviron (sport)|Aviron",
            "Apnée",
            "Baby-foot",
            "Badminton",
            "Base-jump",
            "Baseball",
            "Basket-ball",
            "Bateau-dragon (discipline)|Bateau-Dragon",
            "Biathlon",
            "Billard",
            "Bloc (escalade)",
            "BMX",
            "Boardercross",
            "Bobsleigh",
            "Boccia",
            "Bodyboard",
            "Boomerang",
            "Bowling",
            "Boxe",
            "Bras de fer",
            "Bridge (jeu de carte)",
            "Canicross",
            "Canoë",
            "Canoë-kayak",
            "Canyonisme|Canyoning",
            "Capoeira",
            "Carrom",
            "catch",
            "Cheerleading",
            "Coastering|Coasteering",
            "Combat",
            "Compétition automobile",
            "Course à pied",
            "Course camarguaise",
            "Course d'orientation",
            "Cricket",
            "Croquet",
            "Concours complet d'équitation#Cross|Cross (équitation)",
            "Cross-country",
            "Cross triathlon",
            "Crosse (sport)|Crosse",
            "CrossFit",
            "Culturisme",
            "Curling",
            "Cyclisme",
            "Cyclo-cross",
            "Danse",
            "Danse sportive",
            "Dames",
            "Décathlon",
            "Deltaplane",
            "Duathlon",
            "Dodgeball",
            "Double Dutch",
            "Drift",
            "Échecs",
            "Équitation",
            "Escalade",
            "Escrime",
            "Esport",
            "Floorball",
            "Folkrace",
            "Football",
            "Football américain",
            "Football australien",
            "Football gaélique",
            "Footing",
            "Futsal",
            "Glisse",
            "Golf",
            "Gouren",
            "Grappling",
            "Gymnastique",
            "Gymnastique rythmique",
            "Haka pei",
            "Hakko-Ryu",
            "Haltérophilie",
            "Handball",
            "Hockey",
            "Hockey sur gazon",
            "Hockey sur glace",
            "Horse-ball",
            "Hurling",
            "Hapkido ",
            "Iaïdo",
            "Jeu de paume",
            "Jiujitsu|Ju-Jitsu",
            "Joutes nautiques",
            "Judo",
            "Javelot tir sur cible",
            "Jiu-jitsu brésilien",
            "Jet ski",
            "Kaninhop",
            "Karaté",
            "Karting",
            "Kayak",
            "Kempo",
            "Kendo",
            "Kenjutsu",
            "Kick-boxing",
            "Kitesurfing",
            "Kin-ball",
            "Kobudo",
            "Kung fu",
            "Krav maga",
            "Kyudo",
            "Lancer de disque",
            "Lancer de javelot",
            "Lancer de marteau",
            "Lancer de poids",
            "Luge de course",
            "Lutte",
            "Motoneige",
            "Moto  Vitesse moto|vitesse",
            "Moto  Endurance moto|endurance",
            "Moto Moto-cross|cross",
            "Moto trial",
            "Moto  enduro",
            "Musculation",
            "Marathon (sport)|Marathon",
            "Arts martiaux mixtes|MMA",
            "Naban",
            "Natation",
            "Natation synchronisée",
            "Nautisme (voile)|Nautisme",
            "Netball",
            "Omnikin",
            "Stand up paddle|Paddle",
            "Padel",
            "Paintball",
            "Parachutisme",
            "Parapente",
            "Parkour",
            "Patin à glace",
            "Patinage",
            "Patinage artistique",
            "Patinage de vitesse",
            "Patinage synchronisé",
            "Pêche sportive",
            "Pelote basque",
            "Pentathlon moderne",
            "Pétanque",
            "Pilates",
            "Tennis de table|Ping-Pong",
            "Planche à voile",
            "Planeur",
            "Apnée|Plongée en apnée",
            "Plongée sous-marine|Plongée",
            "Plongeon",
            "Plumfoot",
            "Polo",
            "Qi gong",
            "Quad (roller)|Quad",
            "Quidditch moldu|Quidditch",
            "Qwan Ki Do",
            "Rafting",
            "Rallye automobile",
            "Raquette à neige",
            "Régate",
            "Ringuette",
            "Rink hockey",
            "patins à roulettes|Roller",
            "Roller in line hockey",
            "Rugby à sept",
            "Rugby à XIII",
            "Rugby à XV",
            "Roller derby",
            "Rollersoccer|Roller Soccer",
            "Sambo",
            "Savate",
            "Saut à la perche",
            "Saut à ski",
            "Saut en hauteur",
            "Saut en longueur",
            "Shinty",
            "Skateboard",
            "Inline skater hockey|Skater hockey",
            "Skeleton",
            "Ski",
            "Ski alpin",
            "Ski de fond",
            "Ski nordique",
            "Ski nautique",
            "Slamball",
            "Snowboard",
            "Snowscoot",
            "Snowskate",
            "Softball",
            "Spéléologie",
            "Squash",
            "Step",
            "Sumo",
            "Supermotard",
            "Surf",
            "Tae Bo",
            "Taekwondo",
            "Tai-chi-chuan",
            "Taihojutsu",
            "Taïso",
            "Balle au tambourin|Tambourin",
            "Tango (danse)|Tango",
            "Tau'a rapa nui",
            "Tchoukball",
            "Tennis",
            "Tennis de table",
            "Tennis léger",
            "Tir à l'arc",
            "Tir sportif",
            "Trampoline",
            "Triathlon",
            "Tricking",
            "Triple saut",
            "Trottinette freestyle",
            "Twirling",
            "Ultra-léger motorisé|ULM",
            "Ultimate (sport)|Ultimate",
            "Unihockey",
            "Escalade|Varappe",
            "Vélo tout terrain#Le cross-country|Vélocross (vélo cross-country, VTT)",
            "Nautisme (voile)|Voile",
            "Volata",
            "Volley-ball",
            "Voltige aérienne",
            "Voltige en cercle",
            "Wakeboard",
            "Water-polo",
            "Wing chun",
            "Caster board|Waveboard",
            "Yoga",
            "Yoseikan Budo",
            "Zen Hakko Kaï",
            "Zumba"
        ];
        foreach ($sport as $obj)
            DB::table('sports')->insert([
                'name' => $obj,
            ]);

    }


}
